// This file is generated by scripts/codegen-schema-types.ts.
// Generated from schemas/greenfield/user.schema.json.
// Do not edit by hand; run `npm run codegen:schema-types`.

export type GreenfieldPersistencePlaceholderSchema = UserRecord | ProjectRecord;

export type Identifier = string;

export type Timestamp = string;

export interface UserRecord {
  readonly kind: "user";
  readonly id: Identifier;
  readonly email: string;
  readonly displayName: string;
  readonly createdAt: Timestamp;
}

export interface ProjectRecord {
  readonly kind: "project";
  readonly id: Identifier;
  readonly ownerUserId: Identifier;
  readonly slug: string;
  readonly name: string;
  readonly createdAt: Timestamp;
}
