import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

export interface SchemaTypeOutput {
  schemaPath: string;
  outputPath: string;
  rootTypeName: string;
}

export interface SchemaTypeGenerationResult {
  schemaPath: string;
  outputPath: string;
  status: "current" | "written";
}

export const SCHEMA_TYPE_OUTPUTS: readonly SchemaTypeOutput[] = [
  {
    schemaPath: "schemas/greenfield/user.schema.json",
    outputPath: "schemas/greenfield/user.types.generated.ts",
    rootTypeName: "GreenfieldPersistencePlaceholderSchema",
  },
];

interface SchemaTypeGenerationOptions {
  check?: boolean;
  cwd?: string;
}

interface RenderContext {
  definitions: Record<string, unknown>;
}

export async function generateSchemaTypes(
  options: SchemaTypeGenerationOptions = {},
): Promise<readonly SchemaTypeGenerationResult[]> {
  const cwd = options.cwd ?? process.cwd();
  const results: SchemaTypeGenerationResult[] = [];
  const staleOutputs: string[] = [];

  for (const output of SCHEMA_TYPE_OUTPUTS) {
    const schema = JSON.parse(await readFile(resolve(cwd, output.schemaPath), "utf8")) as unknown;
    const generated = generateTypeModuleFromSchema(schema, output);
    const outputPath = resolve(cwd, output.outputPath);
    const current = await readFileIfExists(outputPath);

    if (current === generated) {
      results.push({ schemaPath: output.schemaPath, outputPath: output.outputPath, status: "current" });
      continue;
    }

    if (options.check) {
      staleOutputs.push(output.outputPath);
      continue;
    }

    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, generated, "utf8");
    results.push({ schemaPath: output.schemaPath, outputPath: output.outputPath, status: "written" });
  }

  if (staleOutputs.length > 0) {
    throw new Error(`Generated schema types are stale: ${staleOutputs.join(", ")}`);
  }

  return results;
}

export function generateTypeModuleFromSchema(schema: unknown, output: SchemaTypeOutput): string {
  const document = assertRecord(schema, output.schemaPath);
  const definitions = assertRecord(document.$defs, `${output.schemaPath}.$defs`);
  const context: RenderContext = { definitions };
  const rootRefs = getRootDefinitionRefs(document, output);
  const lines = [
    "// This file is generated by scripts/codegen-schema-types.ts.",
    `// Generated from ${output.schemaPath}.`,
    "// Do not edit by hand; run `npm run codegen:schema-types`.",
    "",
    `export type ${output.rootTypeName} = ${rootRefs.map(typeNameFromDefinitionName).join(" | ")};`,
    "",
  ];

  for (const [definitionName, definition] of Object.entries(definitions)) {
    lines.push(...renderDefinitionType(definitionName, definition, context), "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderDefinitionType(definitionName: string, definition: unknown, context: RenderContext): string[] {
  const schema = assertRecord(definition, `$defs.${definitionName}`);
  const typeName = typeNameFromDefinitionName(definitionName);

  if (schema.type === "string") {
    return [`export type ${typeName} = string;`];
  }

  if (schema.type === "object") {
    return renderObjectType(typeName, schema, context);
  }

  throw new Error(`Unsupported schema definition ${definitionName}: expected string or object type`);
}

function renderObjectType(typeName: string, schema: Record<string, unknown>, context: RenderContext): string[] {
  const properties = assertRecord(schema.properties, `${typeName}.properties`);
  const required = getStringArray(schema.required, `${typeName}.required`);
  const propertyNames = orderedPropertyNames(properties, required);
  const lines = [`export interface ${typeName} {`];

  for (const propertyName of propertyNames) {
    const property = properties[propertyName];
    const optional = required.includes(propertyName) ? "" : "?";
    lines.push(`  readonly ${renderPropertyKey(propertyName)}${optional}: ${renderPropertyType(property, context)};`);
  }

  lines.push("}");
  return lines;
}

function renderPropertyType(schema: unknown, context: RenderContext): string {
  const property = assertRecord(schema, "property");

  if (typeof property.$ref === "string") {
    return typeNameFromDefinitionName(definitionNameFromRef(property.$ref, context));
  }

  if ("const" in property) {
    return JSON.stringify(property.const);
  }

  if (property.type === "string") {
    return "string";
  }

  if (Array.isArray(property.oneOf)) {
    return property.oneOf.map((entry) => renderPropertyType(entry, context)).join(" | ");
  }

  throw new Error(`Unsupported schema property: ${JSON.stringify(property)}`);
}

function getRootDefinitionRefs(document: Record<string, unknown>, output: SchemaTypeOutput): string[] {
  if (!Array.isArray(document.oneOf) || document.oneOf.length === 0) {
    throw new Error(`${output.schemaPath} must define a non-empty root oneOf`);
  }

  return document.oneOf.map((entry, index) => {
    const ref = assertRecord(entry, `${output.schemaPath}.oneOf[${index}]`).$ref;
    if (typeof ref !== "string") {
      throw new Error(`${output.schemaPath}.oneOf[${index}] must contain a $ref string`);
    }
    return definitionNameFromRef(ref, { definitions: assertRecord(document.$defs, `${output.schemaPath}.$defs`) });
  });
}

function definitionNameFromRef(ref: string, context: RenderContext): string {
  const prefix = "#/$defs/";
  if (!ref.startsWith(prefix)) {
    throw new Error(`Unsupported $ref ${ref}; only local $defs refs are supported`);
  }

  const definitionName = ref.slice(prefix.length);
  if (!(definitionName in context.definitions)) {
    throw new Error(`Unknown schema definition ref ${ref}`);
  }
  return definitionName;
}

function typeNameFromDefinitionName(definitionName: string): string {
  const pascal = definitionName
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");

  if (!pascal || !/^[A-Z]/.test(pascal)) {
    throw new Error(`Cannot derive a TypeScript type name from schema definition ${definitionName}`);
  }

  return pascal;
}

function orderedPropertyNames(properties: Record<string, unknown>, required: readonly string[]): string[] {
  const propertyNames = Object.keys(properties);
  const requiredFirst = required.filter((propertyName) => propertyNames.includes(propertyName));
  const optional = propertyNames.filter((propertyName) => !requiredFirst.includes(propertyName));
  return [...requiredFirst, ...optional];
}

function renderPropertyKey(propertyName: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(propertyName) ? propertyName : JSON.stringify(propertyName);
}

function assertRecord(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

function getStringArray(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) {
    throw new Error(`${label} must be a string array`);
  }
  return value as string[];
}

async function readFileIfExists(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const results = await generateSchemaTypes({ check });

  for (const result of results) {
    console.log(`${result.status}: ${result.outputPath}`);
  }
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
